### ISSUE TITLE
Exception while evaluation

### ISSUE THREAD

**Issue by altostratous** [nniranjhana/Soft-TensorFI#4]
After installing like this:
pip install tensorflow
python tests/nn-minst.py test

I get into this exception:

```

Traceback (most recent call last):
  File "/home/ali/Desktop/Code/TF-Injector/tests/nn-mnist.py", line 45, in <module>
    tfi.inject(model=model, confFile="confFiles/sample.yaml")
  File "/home/ali/Desktop/Code/TF-Injector/src/tfi.py", line 14, in inject
    return fiFunc(fiConf, **kwargs)
  File "/home/ali/Desktop/Code/TF-Injector/src/tfi.py", line 62, in mutate
    val_ = bitflip(val, pos)
  File "/home/ali/Desktop/Code/TF-Injector/src/tfi.py", line 40, in bitflip
    f_ = pack('f', f)
struct.error: required argument is not a float

```

I think there is some essential miss-configuration with me.

here are the versions I'm using:

```
absl-py==0.11.0
astunparse==1.6.3
cachetools==4.2.1
certifi==2020.12.5
chardet==4.0.0
flatbuffers==1.12
gast==0.3.3
google-auth==1.26.1
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
idna==2.10
Keras-Preprocessing==1.1.2
Markdown==3.3.3
numpy==1.19.5
oauthlib==3.1.0
opt-einsum==3.3.0
protobuf==3.14.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7
six==1.15.0
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.4.1
tensorflow-estimator==2.4.0
termcolor==1.1.0
typing-extensions==3.7.4.3
urllib3==1.26.3
Werkzeug==1.0.1
wrapt==1.12.1


```

**Comment by altostratous** [comment]
My bad I had a bug using the correct python for running this.
